Feat/arturo/pp 51 event hall redux
alonsosfera/event-ticket-project pull request #32
Opened 2024-09-26 17:40 UTC by ArturoContrerasChaparro

2024-09-26 19:51 UTC, alonsosfera requested changes

2024-09-26 19:51 UTC, alonsosfera commented on components/rooms/new-room-component.js
> +          <Input placeholder="Salón campestre" />
Hay que usar un placeholder más genérico, algo "Salón ..."

2024-09-26 19:51 UTC, alonsosfera commented on components/rooms/new-room-component.js
> +          <Input placeholder="Avenida 20 sur 201" />
Este no es una dirección, es un link de google maps

2024-09-26 19:51 UTC, alonsosfera commented on components/rooms/new-room-component.js
> +          <Input placeholder="Capacidad" />
Creo que este tiene que ser Input.Number

2024-09-26 19:51 UTC, alonsosfera commented on components/rooms/rooms-component.js
> +  const rooms = useSelector(state => state.roomsSlice.list)
En la linea 14 ya estas usando el useSelector para roomsSlice, ahí mismo puedes sacar la list

2024-09-26 19:51 UTC, alonsosfera commented on components/rooms/rooms-header-component.js
> +const RoomsHeaderComponent = ({ showModal }) => {
El nombre debería de ser onShowModal porque es una función

2024-09-30 18:02 UTC, AlexArmendariz03 approved these changes

2024-10-09 16:38 UTC, alonsosfera approved these changes

2024-10-09 16:38 UTC, merged